# Generated by Django 4.0.4 on 2022-06-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.AutoField(primary_key=True, serialize=False)),
                ('nomComida', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='foto_comida')),
                ('descripcion', models.CharField(max_length=1000)),
                ('costo', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nomRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomUsuario', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=30)),
                ('RolUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.rolusuario')),
            ],
        ),
    ]
