# Generated by Django 4.0.4 on 2022-06-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_usuario_rolusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='RolUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.rolusuario'),
        ),
    ]
